/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-10-31 14:44:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar/footerCommon.jsp", Long.valueOf(1667040362002L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Sign Up Form </title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"NavBar\" style=\" height: 3.75em; width : 100%; background-color:#173F5F;\">\r\n");
      out.write("		<img src=\"images/cec.png\" alt=\"CEC\" style=\"height:3.75em; width:4.75em; padding-left:1em;  text-align:center;\">\r\n");
      out.write("		\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"topOne\" style=\" left: 0; top: 0;height:2em; width: 100%; background-color:#3CAEA3; color: black; text-align: center;\"><b>Welcome to City Events Corporation. Where Events meet Intelligence !!!</b></b></div>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"sign-in\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"signin-content\">\r\n");
      out.write("	<div class=\"signin-image\">\r\n");
      out.write("	<figure>\r\n");
      out.write("	<img src=\"images/pic1.jpg\" alt=\"sing in image\">\r\n");
      out.write("	</figure>\r\n");
      out.write("	<a href=\"Registration.jsp\" class=\"signup-image-link\">Create an	account</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"signin-form\">\r\n");
      out.write("	<h2 class=\"form-title\">Log In</h2>\r\n");
      out.write("	\r\n");
      out.write("	<form method=\"post\" action=\"LoginServlet\" class=\"register-form\"	id=\"login-form\">\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"form-group\">\r\n");
      out.write("	<label for=\"username\"><i class=\"zmdi zmdi-account material-icons-name\"></i></label>\r\n");
      out.write("	 <input	type=\"text\" name=\"email\" id=\"username\"	placeholder=\"Enter email\"  required=\"required\"/>\r\n");
      out.write("		</div>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("	<div class=\"form-group\">\r\n");
      out.write("	<label for=\"password\"><i class=\"zmdi zmdi-lock\"></i></label>\r\n");
      out.write("	 <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\" required=\"required\"  />\r\n");
      out.write("	</div>\r\n");
      out.write("						\r\n");
      out.write("	<div class=\"form-group form-button\">\r\n");
      out.write("	<input type=\"submit\" name=\"signin\" id=\"signin\"\r\n");
      out.write("	class=\"form-submit\" value=\"Log in\"  />\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("						\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"footer\" style=\"position: fixed; left: 0; bottom: 0;height:5.5em; width: 100%; background-color:#173F5F; color: white; text-align: center;\">\r\n");
      out.write("		<img src=\"images/cec2.png\" alt=\"CEC\" style=\"height:2.75em; width:3.75em; padding-left:1em;\"> \r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<b style=\"text-align:center;float:left; padding:1em; color:yellow;\"> Copyright 2022 @ City Events Corporation Ltd.</b>\r\n");
      out.write("\r\n");
      out.write("		<img src=\"images/insta.jpg\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/facebook.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/LinkedIn.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/twitter.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/Pinterest.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("	\r\n");
      out.write("	<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
