/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-11-01 04:27:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cybage.model.Registration;

public final class updateUserProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/E:/Mini%20Project%20-JAVA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/EVENT_MANAGAMENT_SYSTEM/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666093226800L));
    _jspx_dependants.put("/navbar/footerCommon.jsp", Long.valueOf(1667040362002L));
    _jspx_dependants.put("/navbar/userNavbar.jsp", Long.valueOf(1667276854247L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.cybage.model.Registration");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"NavBar\" style=\" left: 0; height: 3.75em; width : 100%; background-color:#173F5F;\">\r\n");
      out.write("		<img src=\"images/cec.png\" alt=\"CEC\" style=\"height:3.75em; width:4.75em; padding-left:1em;  text-align:center;\">\r\n");
      out.write("		<a href =\"LogoutController\" style=\"float:right; padding:1em; \"text-decoration: none;><button>LOGOUT</button></a>\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"UserProfileUpdateServlet\" style=\"float:right; padding:1em; color:white; text-decoration: none;\"><b>Update Profile</b></a>\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"ViewUserEvents\" style=\"float:right; padding:1em; color:white; text-decoration: none;\"><b>Booking list</b></a>\r\n");
      out.write("		<a href=\"UserViewEvents\" style=\"float:right; padding:1em; color:white; text-decoration: none;\"><b>Events</b></a>\r\n");
      out.write("		<a href=\"userPage.jsp\" style=\"float:right; padding:1em; color:white; text-decoration: none;\"><b>Home</b></a>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Registration userDetails=(Registration)request.getAttribute("userDetails"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1> Update Profile</h1>\r\n");
      out.write("<form action=\"UserProfileUpdateServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"number\" name=\"userId\" value=\"");
      out.print(userDetails.getUserID());
      out.write("\">\r\n");
      out.write("<input type=\"text\" name=\"userName\" value=\"");
      out.print(userDetails.getName());
      out.write("\">\r\n");
      out.write("<input type=\"text\" name=\"userEmail\" value=\"");
      out.print(userDetails.getEmail());
      out.write("\">\r\n");
      out.write("<input type=\"password\" name=\"userPassword\" value=\"");
      out.print(userDetails.getPassword() );
      out.write("\">\r\n");
      out.write("<input type=\"text\" name=\"userContact\" value=\"");
      out.print(userDetails.getContact() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"submit\">\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"footer\" style=\"position: fixed; left: 0; bottom: 0;height:5.5em; width: 100%; background-color:#173F5F; color: white; text-align: center;\">\r\n");
      out.write("		<img src=\"images/cec2.png\" alt=\"CEC\" style=\"height:2.75em; width:3.75em; padding-left:1em;\"> \r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<b style=\"text-align:center;float:left; padding:1em; color:yellow;\"> Copyright 2022 @ City Events Corporation Ltd.</b>\r\n");
      out.write("\r\n");
      out.write("		<img src=\"images/insta.jpg\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/facebook.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/LinkedIn.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/twitter.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("		<img src=\"images/Pinterest.png\" alt=\"CEC\" style=\"height:1.5em; width:1.5em; float:right; padding:1em;\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
